### PR TITLE
Overhaul of main functions.

### PR DESCRIPTION
**Pull request by n-tdi**
Made the main logic loop only use one loop with more clarity for the next developer that touches it. Fixed grammar throughout the plugin. Added a Debugger class with a debug method that checks if debugging is enabled so you don't have to check with an if statement each time you want to debug. Got rid of a player check in the command has Sender also has a permission.

### CODE REVIEW

**Comment by Hutch79** [comment]
Hey @n-tdi 
Thanks very much for your further look into my code!

Currently, I'm quite busy, but I managed to give everything a brief look.
I'll try to give everything a proper look and merge it into the repo afterwards soon.

Thank you very much for your feedback and therefore helping me to develop my skills further!

**Comment by n-tdi** [comment]
No problem, take your time to review.

The biggest thing to understand is that when you look through all the config commands, instead of using two loops and breaking out of the second one each time. Use the `continue;` function which skips the current loop and goes on to the next one.

**Comment by n-tdi** [comment]
I'll make a new PR. Didn't mean to close.

**Comment by n-tdi** [comment]
When will this be merged @Hutch79  ?

**Comment by Hutch79** [comment]
Hey @n-tdi 
Sorry for the long silence.

I got a long lunchtime today and probably find time to look into it in detail.

I already had a quick overview of the improvements, and they look really good and help me to improve myself.
- The `continue;` was something I searched for a long time, but it seems I just had the wrong keywords in google.
- The change from while to for is something I need to look into further because I don't really get how for works ^^'
- Also, the change for the debug messages is something small, but it's something that make it seam more organized, and also it's better to change.

**Comment by Hutch79** [comment]
I will test the Plugin and then publish it on SpigotMC as well as in the releases.
Thank you very much!

**Comment by n-tdi** [comment]
Alright, thank you!

**Comment by n-tdi** [comment]
> Hey @n-tdi Sorry for the long silence.
> 
> I got a long lunchtime today and probably find time to look into it in detail.
> 
> I already had a quick overview of the improvements, and they look really good and help me to improve myself.
> 
> * The `continue;` was something I searched for a long time, but it seems I just had the wrong keywords in google.
> * The change from while to for is something I need to look into further because I don't really get how for works ^^'
> * Also, the change for the debug messages is something small, but it's something that make it seam more organized, and also it's better to change.
> 
> Btw. the grammar thing ^^ I really need something like LanguageTool in my IDE XD Thank you very much!

Haha, I’m glad I can help you. Feel free to DM me on discord Ntdi#0002 and I can explain for loops or anything else to you.

**Comment by Hutch79** [comment]
Thank you very much!
I will send you a friend request.

**Comment by n-tdi** [comment]
One last note, the debugger class I made isn’t perfect. You could make it automatically add the prefix and such. I just got lazy 😂

**Comment by Hutch79** [comment]
Yea I have already planned that ^^
I also found a way to automatically set the Plugin name as prefix so I can be lazy and copy and paste it to a new plugin ^^

**Comment by n-tdi** [comment]
> Yea I have already planned that ^^
> I also found a way to automatically set the Plugin name as prefix so I can be lazy and copy and paste it to a new plugin ^^

That’s genius! I wish you the best.

**Pull request merged**
